services:
  backend:
    build: ./backend
    container_name: todo_crud_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: todo_crud_frontend
    env_file:
      - ./frontend/.env
    environment:
      - VITE_URL=http://localhost:8001/api
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: todo_crud_nginx
    ports:
      - "8001:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html  # index.html
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media

  db:
    image: postgres:16.0
    container_name: todo_crud_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data:
  node_modules: